### ISSUE TITLE
Issue with not refreshing playlists

### ISSUE THREAD

**Issue by tzachb** [kubatek94/DeezerKodi#15]
Hello kubatek94

i really like your great plugin , but unfortunately i cant use all my playlists as i only see one playist all the rest are not updated in kodi it seems to work on cache only , i believe you are very busy but any chance you could make some effort and look in to this i really appreciate if you can release a new verion that fix it soon.

Thank you in advance .

Tzach

**Comment by kubatek94** [comment]
Thanks for reporting, resolved in 0.0.3.
