### ISSUE TITLE
error in Kodi 16.1 "Jarvis"

### ISSUE THREAD

**Issue by batarela** [kubatek94/DeezerKodi#2]
I have premium + account bat app not working gives error. here is log file: http://pastebin.com/g3euFy4p

**Comment by kubatek94** [comment]
Hi. Windows installation of python is missing the requests library. You can install it from Kodi addon installation menu. Check this link for screen shot on where to install it and tell me if it helped:

http://forum.kodi.tv/showthread.php?tid=201894&pid=1949185#pid1949185

**Comment by batarela** [comment]
I have installed Requests 2.9.1 all the time and many addons which use the module and have no problem with any of them.

 

Regards

**Comment by kubatek94** [comment]
Hi,
I have updated the addon with a dependency for "requests" library and also set up the github repository in a way where the addon will auto update itself when I will upload new version here (and it should automatically download the dependency if missing during installation). Try uninstalling the existing addon and install it again from the .zip in the repository, it should work this time (it works for me on Kodi 16.1, although I am running it on linux). Please let me know if it resolves your issue.

**Comment by batarela** [comment]
Thank you.
Now everything is fine . Do deezer API allows off-line play. If this can, then everything would be perfect.

regards

**Comment by kubatek94** [comment]
Great, thanks for your feedback. I am still working on this project, although I don't have as much time as I would like. I will add marking songs for off-line playback this month.
